# Generated by Django 4.2.2 on 2025-04-03 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chess_models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='game_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='games_set', to='chess_models.game'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='round_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='rounds_set', to='chess_models.round'),
        ),
        migrations.AlterField(
            model_name='game',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='games', to='chess_models.round'),
        ),
        migrations.AlterField(
            model_name='round',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='rounds', to='chess_models.tournament'),
        ),
    ]
