# Generated by Django 4.2.2 on 2025-04-04 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chess_models', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='game_set',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='round_set',
        ),
    ]
