# Generated by Django 4.2.2 on 2025-04-03 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess_models', '0002_round_game_set_tournament_round_set_alter_game_round_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='round_set',
        ),
        migrations.AddField(
            model_name='tournament',
            name='round_set',
            field=models.ManyToManyField(blank=True, related_name='tournaments', to='chess_models.round'),
        ),
    ]
