# Generated by Django 4.2.2 on 2025-04-04 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chess_models', '0003_alter_round_tournament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='chess_models.round'),
        ),
    ]
