# Generated by Django 4.2.2 on 2025-04-03 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess_models', '0003_remove_tournament_round_set_tournament_round_set'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='game_set',
        ),
        migrations.AddField(
            model_name='round',
            name='game_set',
            field=models.ManyToManyField(blank=True, related_name='games_set', to='chess_models.round'),
        ),
    ]
