# Generated by Django 4.2.2 on 2025-04-03 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess_models', '0004_remove_round_game_set_round_game_set'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='game_set',
            field=models.ManyToManyField(blank=True, related_name='games_set', to='chess_models.game'),
        ),
    ]
