# Generated by Django 4.2.2 on 2025-04-07 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess_models', '0004_alter_game_round'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='start_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
