# Generated by Django 4.2.2 on 2025-04-07 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chess_models', '0005_alter_tournament_start_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='administrariveUser',
            new_name='administrativeUser',
        ),
    ]
