# Generated by Django 4.2.2 on 2025-05-06 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chess_models', '0006_rename_administrariveuser_tournament_administrativeuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chess_models.tournament'),
        ),
    ]
